# Generated by Django 3.1.7 on 2021-02-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0002_auto_20210226_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('from_image', models.ImageField(upload_to=None)),
                ('to_image', models.ImageField(upload_to=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='imageuploader.image')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-date'],
            },
        ),
    ]
