# Generated by Django 3.1.7 on 2021-02-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0003_imageaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='update',
        ),
        migrations.AlterField(
            model_name='imageaction',
            name='from_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='imageaction',
            name='to_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
