# Generated by Django 3.1.7 on 2021-02-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0004_auto_20210226_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageaction',
            name='to_image',
        ),
    ]
